### ISSUE TITLE
[Batch] Complete Olinda v1

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/olinda#8]
The Olinda package has had several stages of development. We aim now to complete a fully working version of Olinda, v1, which will be focused on ZairaChem models (see ersilia-os/zaira-chem#32) but have the modular functionality to easily adapt to other models, like third-party models in the Ersilia Model Hub. 

To that end, there are several improvements to be made before merging @JHlozek branch into the main repository. Once this v1 is complete, @miquelduranfrigola and @GemmaTuron will work to convert ZairaChem to individual modules (ersilia-os/zaira-chem#30) and in turn, Olinda if necessary. 

Below a general guide of the tasks to be completed to that end, and the issues related to it:

- [x] Include automated check in Olinda for the descriptors that are calculated #9 
- [x] Olinda install instructions modularity with ZairaChem optional #10 
- [x] Adding CLI commands in Olinda #11 
- [x] Adding CLI command to ZairaChem ersilia-os/zaira-chem#47
- [x] Refactoring Olinda's files and repo structure to standard #12 
- [x] Eliminate unnecessary prints #13 
- [x] Identify best parameters for ZairaChem Model Distillation ersilia-os/zaira-chem#46
- [x] Benchmark Olinda with TDC dataset #7

**Comment by GemmaTuron** [comment]
@JHlozek has made an amazing work on all the above issues. Please open a PR to merge both Olinda and ZairaChem forks into the main code and we (@miquelduranfrigola and @GemmaTuron) will take it up. We will open issues related to the reformatting and modularity of Zairachem/Olinda + documentation for end users as we advance
